import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import ReduxProvider from "@/components/providers/ReduxProvider";

import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "900"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} scroll-smooth `}>
      <body
        suppressHydrationWarning={true}
        className="min-h-screen max-w-[100vw] antialiased font-normal overflow-x-hidden font-sans "
      >
        <ReduxProvider>{children}</ReduxProvider>

        <Toaster position="top-right" className="z-[1000000000]" richColors />
      </body>
    </html>
  );
}
